/* AUTHENTICATION */ 

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

/* INFO_GET_STATUS */

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

/* LOGOUT */
export const AUTH_LOGOUT = "AUTH_LOGOUT";

/* AUTH_UPDATE */
export const AUTH_STATUS_UPDATE = "AUTH_STATUS_UPDATE";
export const AUTH_STATUS_UPDATE_SUCCESS = "AUTH_STATUS_UPDATE_SUCCESS";
export const AUTH_STATUS_UPDATE_FAILURE = "AUTH_STATUS_UPDATE_FAILURE";


/* AUTH_DELETE_USER */
export const AUTH_STATUS_DELETE = "AUTH_STATUS_DELETE";
export const AUTH_STATUS_DELETE_SUCCESS = "AUTH_STATUS_DELETE_SUCCESS";
export const AUTH_STATUS_DELETE_FAILURE = "AUTH_STATUS_DELETE_FAILURE";

/* BOARD CONTENT WRITE */
export const BOARD_WRITE = "BOARD_WRITE";
export const BOARD_WRITE_SUCCESS = "BOARD_WRITE_SUCCESS";
export const BOARD_WRITE_FAILURE = "BOARD_WRITE_FAILURE";

/* BOARD GET LIST */
export const BOARD_GET_LIST = "BOARD_GET_LIST";
export const BOARD_GET_LIST_SUCCESS = "BOARD_GET_LIST_SUCCESS";
export const BOARD_GET_LIST_FAILURE = "BOARD_GET_LIST_FAILURE";
